on:
  pull_request:
    branches: [debugging]
  push:
    branches: [debugging]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Zip Files
        working-directory: /dist
        run: zip -r ./kaiserschlacht.zip ./*

